// <auto-generated />
namespace avizevimde.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class asddsa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asddsa));
        
        string IMigrationMetadata.Id
        {
            get { return "201304300223590_asddsa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
